# Generated by Django 5.2.16 on 2026-07-22 08:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0004_hotel_review_enabled_hotel_review_low_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Считается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('export_format', models.CharField(default='csv', max_length=8)),
                ('kind', models.CharField(default='breakdown', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('file', models.CharField(blank=True, max_length=512)),
                ('row_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.UUIDField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_export',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('bus_event_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('business_date', models.DateField(db_index=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('measures', models.JSONField(blank=True, default=dict)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['occurred_at', 'created_at'],
                'indexes': [models.Index(fields=['hotel', 'business_date', 'kind'], name='analytics_e_hotel_i_8dd873_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'dedupe_key'), name='uniq_analytics_event')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(db_index=True)),
                ('item_key', models.CharField(max_length=64)),
                ('category_key', models.CharField(blank=True, max_length=64)),
                ('offering_type', models.CharField(blank=True, max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('revenue_minor', models.BigIntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_item_daily',
                'indexes': [models.Index(fields=['hotel', 'business_date'], name='analytics_i_hotel_i_3259b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'business_date', 'item_key'), name='uniq_item_daily')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModifierDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(db_index=True)),
                ('modifier_key', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_modifier_daily',
                'constraints': [models.UniqueConstraint(fields=('hotel', 'business_date', 'modifier_key'), name='uniq_modifier_daily')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(db_index=True)),
                ('offering_type', models.CharField(blank=True, max_length=32)),
                ('point_key', models.CharField(blank=True, max_length=64)),
                ('location_key', models.CharField(blank=True, max_length=64)),
                ('entry_method', models.CharField(blank=True, max_length=32)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('orders_count', models.IntegerField(default=0)),
                ('revenue_minor', models.BigIntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('off_hours_count', models.IntegerField(default=0)),
                ('reaction_seconds_sum', models.BigIntegerField(default=0)),
                ('reaction_count', models.IntegerField(default=0)),
                ('fulfil_seconds_sum', models.BigIntegerField(default=0)),
                ('fulfil_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_order_daily',
                'indexes': [models.Index(fields=['hotel', 'business_date'], name='analytics_o_hotel_i_d64c25_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'business_date', 'offering_type', 'point_key', 'location_key', 'entry_method', 'device', 'language'), name='uniq_order_daily')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(db_index=True)),
                ('point_key', models.CharField(blank=True, max_length=64)),
                ('offering_type', models.CharField(blank=True, max_length=32)),
                ('reviews_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_review_daily',
                'constraints': [models.UniqueConstraint(fields=('hotel', 'business_date', 'point_key', 'offering_type'), name='uniq_review_daily')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SessionDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(db_index=True)),
                ('entry_method', models.CharField(blank=True, max_length=32)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('sessions_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'analytics_session_daily',
                'constraints': [models.UniqueConstraint(fields=('hotel', 'business_date', 'entry_method', 'device', 'language'), name='uniq_session_daily')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
