# Generated by Django 5.2.16 on 2026-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('hotels', '0004_hotel_review_enabled_hotel_review_low_threshold'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemdaily',
            name='uniq_item_daily',
        ),
        migrations.RemoveConstraint(
            model_name='modifierdaily',
            name='uniq_modifier_daily',
        ),
        migrations.AddField(
            model_name='itemdaily',
            name='point_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='modifierdaily',
            name='point_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='itemdaily',
            constraint=models.UniqueConstraint(fields=('hotel', 'business_date', 'item_key', 'point_key'), name='uniq_item_daily'),
        ),
        migrations.AddConstraint(
            model_name='modifierdaily',
            constraint=models.UniqueConstraint(fields=('hotel', 'business_date', 'modifier_key', 'point_key'), name='uniq_modifier_daily'),
        ),
    ]
