# Generated by Django 5.2.16 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_itemdaily_uniq_item_daily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsexport',
            name='file',
        ),
        migrations.AddField(
            model_name='analyticsexport',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsexport',
            name='content_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='analyticsexport',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
