# Generated by Django 5.2.16 on 2026-07-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_analyticsexport_file_analyticsexport_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdaily',
            name='delivery_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdaily',
            name='service_fee_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdaily',
            name='tax_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdaily',
            name='tip_minor',
            field=models.BigIntegerField(default=0),
        ),
    ]
