# Generated by Django 5.2.17 on 2026-10-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_order_daily_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdaily',
            name='cancelled_priced_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdaily',
            name='cancelled_revenue_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdaily',
            name='priced_count',
            field=models.IntegerField(default=0),
        ),
    ]
