# Generated by Django 5.2.17 on 2026-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_avg_check_measures'),
        ('hotels', '0042_telegram_bot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewdaily',
            name='uniq_review_daily',
        ),
        migrations.AddField(
            model_name='reviewdaily',
            name='part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='reviewdaily',
            constraint=models.UniqueConstraint(fields=('hotel', 'business_date', 'point_key', 'offering_type', 'part'), name='uniq_review_daily_part'),
        ),
    ]
