"""
Журнал событий уведомлений — отдельными таблицами от журнала эскалации.

Журнал эскалации требует заказ, и это правильно; события без заказа
(оформление, сообщение гостя, низкая оценка) пишутся сюда: факт события и его
доставки по каналам — двумя таблицами, чтобы ни у одной строки не было
половины пустых полей. Данных не переносит: прежние рассылки нигде не
записывались, переносить нечего.
"""

# Generated by Django 5.2.17 on 2026-09-16 13:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0033_room_fund_fields'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('pending', 'Рассылается'), ('sent', 'Разослано'), ('partial', 'Разослано не всем'), ('failed', 'Не доставлено никому'), ('no_recipients', 'Некому отправить')], default='pending', max_length=16)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('execution_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.executionpoint')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'notifications_event',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=32)),
                ('channel_title', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка канала'), ('skipped', 'Пропущено'), ('cancelled', 'Погашено (заказ приняли)')], default='scheduled', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notificationchannel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.eventrecord')),
            ],
            options={
                'db_table': 'notifications_event_delivery',
                'ordering': ['created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='eventrecord',
            index=models.Index(fields=['hotel', 'code', '-created_at'], name='notificatio_hotel_i_11e527_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrecord',
            constraint=models.UniqueConstraint(fields=('hotel', 'dedupe_key'), name='uniq_notification_event_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='eventdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('hotel', 'record', 'channel'), name='uniq_event_delivery_per_channel'),
        ),
    ]
