# Generated by Django 5.2.17 on 2026-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_one_active_rule_per_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerBotState',
            fields=[
                ('messenger', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('no_token', 'Токен не задан'), ('rejected', 'Токен не принят'), ('conflict', 'Бота опрашивает другой сервер'), ('error', 'Мессенджер недоступен'), ('ok', 'На связи')], default='no_token', max_length=16)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('token_tail', models.CharField(blank=True, max_length=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('update_offset', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'notifications_bot_state',
            },
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='last_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='via_platform_bot',
            field=models.BooleanField(default=False),
        ),
    ]
