# Generated by Django 5.2.17 on 2026-09-18 12:56

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_staff_contacts'),
        ('hotels', '0039_translatable_strings_to_maps'),
        ('media', '0006_alter_mediaasset_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('title', apps.core.fields.TranslatableField()),
                ('subtitle', apps.core.fields.TranslatableField()),
                ('size', models.CharField(choices=[('s', 'Узкий'), ('m', 'Средний'), ('l', 'Крупный')], default='m', max_length=1)),
                ('placement', models.CharField(choices=[('top', 'Вверху витрины'), ('bottom', 'Внизу витрины')], default='top', max_length=8)),
                ('action', models.CharField(choices=[('none', 'Без действия'), ('link', 'Внешняя ссылка'), ('venue', 'Наше заведение'), ('page', 'Страница с описанием')], default='none', max_length=8)),
                ('action_url', models.URLField(blank=True, max_length=512)),
                ('page_title', apps.core.fields.TranslatableField()),
                ('page_body', apps.core.fields.TranslatableField()),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('first_visit_only', models.BooleanField(default=False)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('action_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.service')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'promo_banner',
                'ordering': ['-priority', 'created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.mediaasset')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promo.banner')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'promo_banner_image',
                'ordering': ['sort_order'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BannerRoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promo.banner')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hotels.roomcategory')),
            ],
            options={
                'db_table': 'promo_banner_category',
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='banner',
            name='room_categories',
            field=models.ManyToManyField(blank=True, related_name='banners', through='promo.BannerRoomCategory', to='hotels.roomcategory'),
        ),
        migrations.CreateModel(
            name='BannerView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('last_click_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('room_category', models.CharField(blank=True, max_length=64)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='promo.banner')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_views', to='accounts.guestsession')),
            ],
            options={
                'db_table': 'promo_banner_view',
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='bannerroomcategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'banner', 'room_category'), name='uniq_banner_room_category'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['hotel', 'is_active', 'placement'], name='promo_banne_hotel_i_73b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerview',
            index=models.Index(fields=['hotel', 'banner', 'shown_at'], name='promo_banne_hotel_i_99a12b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bannerview',
            constraint=models.UniqueConstraint(fields=('hotel', 'banner', 'session'), name='uniq_banner_view_per_session'),
        ),
    ]
