# Generated by Django 5.2.16 on 2026-07-21 11:33

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor_type', models.CharField(choices=[('staff', 'Сотрудник'), ('guest', 'Гость'), ('platform', 'Платформа'), ('system', 'Система')], default='system', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('impersonated_by', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hotels.hotel')),
            ],
            options={
                'db_table': 'core_audit_log',
                'indexes': [models.Index(fields=['hotel', '-created_at'], name='core_audit__hotel_i_69f811_idx')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'core_idempotency_key',
                'constraints': [models.UniqueConstraint(fields=('hotel', 'scope', 'key'), name='uniq_idempotency_per_hotel')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
