# Generated by Django 5.2.17 on 2026-09-14 21:56

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rls_brand_version'),
        ('hotels', '0030_brand_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('took_ms', models.PositiveIntegerField(default=0)),
                ('due_count', models.PositiveIntegerField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('done_last_tick', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'core_scheduler_heartbeat',
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.SlugField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Ждёт срока'), ('done', 'Выполнено'), ('skipped', 'Не состоялась'), ('failed', 'Сбой'), ('cancelled', 'Отменено')], default='pending', max_length=16)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=180)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'core_scheduled_job',
                'ordering': ['run_at'],
                'indexes': [models.Index(fields=['hotel', 'status', 'run_at'], name='core_schedu_hotel_i_569971_idx'), models.Index(fields=['status', 'run_at'], name='core_schedu_status_24897d_idx')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
