# Generated by Django 5.2.16 on 2026-07-21 11:33

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField(help_text='Сквозной номер в рамках отеля')),
                ('type', models.CharField(choices=[('cart', 'Корзина (несколько позиций)'), ('request', 'Заявка (одно действие)')], default='cart', max_length=16)),
                ('location_refinement', models.CharField(blank=True, help_text='Шезлонг №, столик № и т.п.', max_length=128)),
                ('delivery_mode', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=16)),
                ('requested_time', models.DateTimeField(blank=True, help_text='«К 19:00» — хранится в UTC, показывается в TZ отеля', null=True)),
                ('comment', models.TextField(blank=True)),
                ('total', models.IntegerField(default=0, help_text='В минимальных единицах')),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('payment_state', models.CharField(default='none', max_length=32)),
                ('pms_folio_ref', models.CharField(blank=True, max_length=128)),
                ('execution_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='hotels.executionpoint')),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.guestsession')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hotels.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='hotels.room')),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('title_snapshot', apps.core.fields.TranslatableField()),
                ('unit_price_snapshot', models.IntegerField(default=0)),
                ('modifiers_snapshot', models.JSONField(blank=True, default=list)),
                ('line_total', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_item',
                'ordering': ['created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatusDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('color_token', models.SlugField(blank=True, max_length=64)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'orders_status_definition',
                'ordering': ['sort_order'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor_type', models.CharField(default='system', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.order')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.statusdefinition')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.statusdefinition')),
            ],
            options={
                'db_table': 'orders_order_status_change',
                'ordering': ['created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.statusdefinition'),
        ),
        migrations.AddConstraint(
            model_name='statusdefinition',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_status_code_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['hotel', 'execution_point', '-created_at'], name='orders_orde_hotel_i_23212a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['hotel', 'status'], name='orders_orde_hotel_i_f51124_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='uniq_order_number_per_hotel'),
        ),
    ]
