# Generated by Django 5.2.16 on 2026-07-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdefinition',
            name='allows_guest_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
