# Generated by Django 5.2.16 on 2026-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_accepted_at_order_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='field_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=0, help_text='В минимальных единицах', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
