# Generated by Django 5.2.16 on 2026-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_field_values_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charges',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_minor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=0, help_text='Итог к показу, в минимальных единицах', null=True),
        ),
    ]
