"""
Закрытие, переоткрытие и место на доске — три поля одной миграцией.

ЗАПОЛНЕНИЕ ИДЁТ ПО ОТЕЛЯМ, И ЭТО НЕ СТИЛЬ, А УСЛОВИЕ РАБОТЫ. На `orders_order`
и `orders_order_status_change` включена RLS, и `RunPython` под обычной ролью
`guestapp` вернёт по ним НОЛЬ СТРОК — не ошибку. Миграция отчитается «OK», не
сделав ничего. Поэтому каждый отель обходится внутри `tenant_context`, который
выставляет сессионную переменную Postgres, на которую опирается политика.

ОТКУДА БЕРЁТСЯ `closed_at`. Из журнала переходов — ПЕРВОЕ попадание в
терминальный статус. Первое, а не последнее: заказ закрывается один раз, и
именно так его уже считает сводка смены. Заказ без такой записи в журнале
остаётся с пустым `closed_at`: выдумать момент закрытия нечем, а поставить
`updated_at` значило бы записать время последней правки как время закрытия — это
не то же самое и разошлось бы с аналитикой ровно там, где мы её чиним.

СКОЛЬКО ТАКИХ ЗАКАЗОВ И ОТКУДА ОНИ. На стенде «crystal» терминальных заказов
1727, момент закрытия нашёлся у 906. Остальные 821 (756 «отменён», 65
«выполнен») закрыты В ОБХОД журнала: статус им проставила команда обслуживания
`clean_test_residue`, которая пишет `order.status = terminal` напрямую. Сводка
смены и аналитика читают тот же журнал, поэтому эти заказы не попадают в их
числа и СЕЙЧАС — пустой `closed_at` сохраняет ровно текущее поведение, а не
ухудшает его. Сама дыра лечится в месте, где она возникла: команда теперь
проставляет `closed_at` вместе со статусом.

ОТКУДА БЕРЁТСЯ `board_position`. Время создания в секундах эпохи. Так первый же
рендер доски после миграции даёт РОВНО ТОТ ЖЕ порядок, что был до неё
(`order_by("created_at")`), и смена не увидит, что под ней что-то поменяли.

`reopened_at` остаётся пустым: переоткрытий до этой миграции не существовало.

ОТКАТ полный: колонки удаляются вместе с данными, обратная функция не нужна и
объявлена пустой — восстанавливать в несуществующих колонках нечего.
"""

# Generated by Django 5.2.17 on 2026-09-12 08:09

from django.conf import settings
from django.db import migrations, models



def fill_closed_and_position(apps_registry, schema_editor):
    """Заполнить момент закрытия и начальные позиции — по каждому отелю."""
    from apps.core.context import tenant_context

    Hotel = apps_registry.get_model("hotels", "Hotel")
    Order = apps_registry.get_model("orders", "Order")
    Change = apps_registry.get_model("orders", "OrderStatusChange")
    db = schema_editor.connection.alias

    for hotel_id in Hotel.objects.using(db).values_list("pk", flat=True):
        with tenant_context(hotel_id):
            orders = list(
                Order.objects.using(db)
                .filter(hotel_id=hotel_id)
                .values_list("pk", "created_at")
            )
            if not orders:
                continue

            # МЕСТО = ВРЕМЯ СОЗДАНИЯ. Порядок доски не меняется ни на строку.
            for order_id, created_at in orders:
                Order.objects.using(db).filter(pk=order_id).update(
                    board_position=created_at.timestamp()
                )

            # ЗАКРЫТИЕ = ПЕРВЫЙ ПЕРЕХОД В ТЕРМИНАЛ. Идём по возрастанию времени и
            # берём первое попадание на заказ: `setdefault` ниже отбрасывает
            # повторные.
            first_terminal: dict = {}
            rows = (
                Change.objects.using(db)
                .filter(order__hotel_id=hotel_id, to_status__is_terminal=True)
                .order_by("created_at")
                .values_list("order_id", "created_at")
            )
            for order_id, moment in rows:
                first_terminal.setdefault(order_id, moment)
            for order_id, moment in first_terminal.items():
                Order.objects.using(db).filter(pk=order_id).update(closed_at=moment)


def drop_nothing(apps_registry, schema_editor):
    """Откат удаляет сами колонки — восстанавливать в них нечего."""


class Migration(migrations.Migration):
    # НЕ ОДНОЙ ТРАНЗАКЦИЕЙ, И ЭТО ВЫНУЖДЕННО.
    #
    # Postgres отказывается строить индекс в той же транзакции, где таблицу уже
    # правили: `cannot CREATE INDEX "orders_order" because it has pending
    # trigger events`. Проверено — миграция падала ровно на первом `AddIndex`.
    #
    # Плата за это — отсутствие «всё или ничего»: упади миграция посередине, в
    # базе останется часть шагов. Поэтому каждый шаг здесь идемпотентен по
    # построению: добавление колонки повторить нельзя, а заполнение (`RunPython`)
    # пишет вычисленные значения, а не приращения, и повторный прогон даёт тот же
    # результат.
    atomic = False

    dependencies = [
        ('accounts', '0006_staff_session'),
        ('hotels', '0029_backfill_theme_source_preset'),
        ('orders', '0008_backfill_status_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='board_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['hotel', 'execution_point', 'board_position', 'created_at'], name='ix_order_board_position'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['hotel', 'execution_point', '-closed_at'], name='ix_order_closed'),
        ),
        migrations.RunPython(fill_closed_and_position, drop_nothing),
    ]
