# Generated by Django 5.2.17 on 2026-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_closed_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('out_of_stock', 'Нет в наличии'), ('guest_refused', 'Гость отказался'), ('no_capacity', 'Некому выполнить'), ('duplicate', 'Дубль заявки'), ('mistake', 'Ошиблись при оформлении'), ('other', 'Другое')], max_length=32),
        ),
    ]
