# Generated by Django 5.2.17 on 2026-09-17 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_thread_per_session_unique'),
        ('orders', '0013_order_placed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='chat.chatthread'),
        ),
    ]
