# Generated by Django 5.2.17 on 2026-10-04 21:53

from django.db import migrations, models


def backfill_actor_names(apps, schema_editor):
    """
    Снимок имени для уже записанной истории — из учёток, включая удалённые.

    По отелям внутри `tenant_context`: на тенантных таблицах RLS, и без
    выставленного отеля обычная роль увидела бы ноль строк и отчиталась бы OK.
    """
    from apps.core.context import tenant_context

    db = schema_editor.connection.alias
    Hotel = apps.get_model("hotels", "Hotel")
    User = apps.get_model("accounts", "User")
    Change = apps.get_model("orders", "OrderStatusChange")
    for hotel in Hotel._base_manager.using(db).all():
        with tenant_context(hotel.pk):
            rows = Change._base_manager.using(db).filter(
                actor_type="staff", actor_id__isnull=False, actor_name=""
            )
            ids = set(rows.values_list("actor_id", flat=True))
            if not ids:
                continue
            names = {
                user.pk: (user.full_name or user.email)[:255]
                for user in User._base_manager.using(db).filter(pk__in=ids)
            }
            for actor_id, name in names.items():
                rows.filter(actor_id=actor_id).update(actor_name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_source_thread'),
        ('accounts', '0008_refresh_rotation'),
        ('hotels', '0042_telegram_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatuschange',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_actor_names, migrations.RunPython.noop),
    ]
