# Generated by Django 5.2.17 on 2026-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_status_change_actor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
