# Generated by Django 5.2.17 on 2026-10-08 19:35

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0043_codes_unique_among_live'),
        ('orders', '0016_order_item_comment_300'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assignee_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=255)),
                ('previous_name', models.CharField(blank=True, max_length=255)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_assignment',
                'ordering': ['created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
