# Generated by Django 5.2.17 on 2026-10-08 21:44

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0043_codes_unique_among_live'),
        ('orders', '0017_order_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='OrderTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('from_title', models.CharField(blank=True, max_length=255)),
                ('to_title', models.CharField(blank=True, max_length=255)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('from_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.executionpoint')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='orders.order')),
                ('to_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.executionpoint')),
            ],
            options={
                'db_table': 'orders_order_transfer',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('order', 'number'), name='uniq_order_transfer_number')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
