/**
 * Redesign-v2 icon registry.
 *
 * Re-exports the icon primitive, every icon component, and a grouped registry
 * used by the styleguide gallery (and available to any screen that wants to map
 * a semantic code to an icon). All icons inherit `currentColor`, so they recolor
 * from theme tokens with no color literal anywhere.
 */
export {
  createIcon,
  ICON_SIZES,
  ICON_STROKE,
  type AppIconProps,
  type AppIconComponent,
  type IconSize,
} from './AppIcon';

export * from './icons';

import type { AppIconComponent } from './AppIcon';
import {
  IconRestaurant,
  IconServices,
  IconSlots,
  IconInfo,
  IconBag,
  IconVegan,
  IconVegetarian,
  IconSpicy,
  IconGlutenFree,
  IconLactoseFree,
  IconNuts,
  IconSeafood,
  IconHalal,
  IconEgg,
  IconMilk,
  IconAdd,
  IconMinus,
  IconEdit,
  IconDelete,
  IconBack,
  IconClose,
  IconSearch,
  IconFilter,
  IconSort,
  IconShare,
  IconDownload,
  IconMore,
  IconCheck,
  IconStatusNew,
  IconStatusAccepted,
  IconStatusPreparing,
  IconStatusReady,
  IconStatusDone,
  IconStatusCancelled,
  IconHome,
  IconOrders,
  IconChat,
  IconAnalytics,
  IconRooms,
  IconStaff,
  IconBrand,
  IconHit,
  IconChefChoice,
  IconDimmer,
  IconCurtain,
  IconThermostat,
  IconSwitch,
  IconScene,
  IconLock,
  IconWifi,
  IconRunning,
  IconOffline,
} from './icons';

export interface IconGroup {
  /** i18n-free key used for the gallery section heading. */
  group: string;
  icons: { name: string; Icon: AppIconComponent }[];
}

/** Flat lookup by name — handy for mapping a semantic code to an icon. */
export const ICON_REGISTRY: Record<string, AppIconComponent> = {
  restaurant: IconRestaurant,
  services: IconServices,
  slots: IconSlots,
  info: IconInfo,
  bag: IconBag,
  vegan: IconVegan,
  vegetarian: IconVegetarian,
  spicy: IconSpicy,
  glutenFree: IconGlutenFree,
  lactoseFree: IconLactoseFree,
  nuts: IconNuts,
  seafood: IconSeafood,
  halal: IconHalal,
  egg: IconEgg,
  milk: IconMilk,
  add: IconAdd,
  minus: IconMinus,
  edit: IconEdit,
  delete: IconDelete,
  back: IconBack,
  close: IconClose,
  search: IconSearch,
  filter: IconFilter,
  sort: IconSort,
  share: IconShare,
  download: IconDownload,
  more: IconMore,
  check: IconCheck,
  statusNew: IconStatusNew,
  statusAccepted: IconStatusAccepted,
  statusPreparing: IconStatusPreparing,
  statusReady: IconStatusReady,
  statusDone: IconStatusDone,
  statusCancelled: IconStatusCancelled,
  home: IconHome,
  orders: IconOrders,
  chat: IconChat,
  analytics: IconAnalytics,
  rooms: IconRooms,
  staff: IconStaff,
  brand: IconBrand,
  hit: IconHit,
  chefChoice: IconChefChoice,
  dimmer: IconDimmer,
  curtain: IconCurtain,
  thermostat: IconThermostat,
  switch: IconSwitch,
  scene: IconScene,
  lock: IconLock,
  wifi: IconWifi,
  running: IconRunning,
  offline: IconOffline,
};

/** Grouped for the styleguide gallery, in display order. */
export const ICON_GROUPS: IconGroup[] = [
  {
    group: 'Storefront',
    icons: [
      { name: 'restaurant', Icon: IconRestaurant },
      { name: 'services', Icon: IconServices },
      { name: 'slots', Icon: IconSlots },
      { name: 'info', Icon: IconInfo },
      { name: 'bag', Icon: IconBag },
    ],
  },
  {
    group: 'Dietary & allergens',
    icons: [
      { name: 'vegan', Icon: IconVegan },
      { name: 'vegetarian', Icon: IconVegetarian },
      { name: 'spicy', Icon: IconSpicy },
      { name: 'glutenFree', Icon: IconGlutenFree },
      { name: 'lactoseFree', Icon: IconLactoseFree },
      { name: 'nuts', Icon: IconNuts },
      { name: 'seafood', Icon: IconSeafood },
      { name: 'halal', Icon: IconHalal },
      { name: 'egg', Icon: IconEgg },
      { name: 'milk', Icon: IconMilk },
    ],
  },
  {
    group: 'Actions',
    icons: [
      { name: 'add', Icon: IconAdd },
      { name: 'minus', Icon: IconMinus },
      { name: 'edit', Icon: IconEdit },
      { name: 'delete', Icon: IconDelete },
      { name: 'back', Icon: IconBack },
      { name: 'close', Icon: IconClose },
      { name: 'search', Icon: IconSearch },
      { name: 'filter', Icon: IconFilter },
      { name: 'sort', Icon: IconSort },
      { name: 'share', Icon: IconShare },
      { name: 'download', Icon: IconDownload },
      { name: 'more', Icon: IconMore },
      { name: 'check', Icon: IconCheck },
    ],
  },
  {
    group: 'Statuses',
    icons: [
      { name: 'statusNew', Icon: IconStatusNew },
      { name: 'statusAccepted', Icon: IconStatusAccepted },
      { name: 'statusPreparing', Icon: IconStatusPreparing },
      { name: 'statusReady', Icon: IconStatusReady },
      { name: 'statusDone', Icon: IconStatusDone },
      { name: 'statusCancelled', Icon: IconStatusCancelled },
    ],
  },
  {
    group: 'Navigation',
    icons: [
      { name: 'home', Icon: IconHome },
      { name: 'orders', Icon: IconOrders },
      { name: 'chat', Icon: IconChat },
      { name: 'info', Icon: IconInfo },
      { name: 'analytics', Icon: IconAnalytics },
      { name: 'rooms', Icon: IconRooms },
      { name: 'staff', Icon: IconStaff },
      { name: 'brand', Icon: IconBrand },
    ],
  },
  {
    group: 'Badges',
    icons: [
      { name: 'hit', Icon: IconHit },
      { name: 'statusNew', Icon: IconStatusNew },
      { name: 'chefChoice', Icon: IconChefChoice },
    ],
  },
  {
    group: 'Room controls',
    icons: [
      { name: 'dimmer', Icon: IconDimmer },
      { name: 'curtain', Icon: IconCurtain },
      { name: 'thermostat', Icon: IconThermostat },
      { name: 'switch', Icon: IconSwitch },
      { name: 'scene', Icon: IconScene },
      { name: 'lock', Icon: IconLock },
      { name: 'wifi', Icon: IconWifi },
      { name: 'running', Icon: IconRunning },
      { name: 'offline', Icon: IconOffline },
    ],
  },
];
