import { webkit } from '@playwright/test'
const BASE = 'http://192.168.1.79:5183'
const OUT = '/Users/olegpronkin/.claude/jobs/aa0fe34b/tmp'
const browser = await webkit.launch()
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'ru-RU', hasTouch: true, deviceScaleFactor: 3 })
const page = await ctx.newPage()
await page.goto(BASE)
await page.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
await page.goto(BASE)
await page.getByTestId('guest-room-input').fill('305')
await page.getByTestId('guest-room-submit').click()
await page.getByTestId('guest-nav-room').click({ timeout: 25000 })
await page.getByTestId('room-page').waitFor({ timeout: 25000 })
await page.waitForTimeout(2500)
await page.screenshot({ path: `${OUT}/g5d-webkit-light.png` })

// Компактное меню: язык и тема на месте.
await page.getByTestId('guest-quick-menu').click()
await page.waitForTimeout(500)
await page.screenshot({ path: `${OUT}/g5d-webkit-menu.png` })
await page.getByTestId('guest-language-ar').click()
await page.waitForTimeout(1500)
console.log('направление:', await page.evaluate(() => document.documentElement.dir))
console.log('горизонтальный разъезд:', await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth))
await page.screenshot({ path: `${OUT}/g5d-webkit-rtl.png` })
await page.getByTestId('guest-quick-menu').click()
await page.getByTestId('guest-language-ru').click()
await page.waitForTimeout(1200)
await page.getByTestId('guest-quick-menu').click()
await page.getByTestId('theme-toggle').click()
await page.waitForTimeout(1200)
await page.screenshot({ path: `${OUT}/g5d-webkit-lighttheme.png` })
console.log('ok')
await browser.close()
