import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: {width: 430, height: 900}, locale: 'ru-RU' })
p.on('pageerror', e => console.log('PAGEERROR', String(e).slice(0,200)))
await p.goto('http://localhost:5183')
await p.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
await p.goto('http://localhost:5183')
await p.getByTestId('guest-room-input').fill('305')
await p.getByTestId('guest-room-submit').click()
await p.getByTestId('guest-nav-room').click()
await p.getByTestId('room-page').waitFor({ timeout: 20000 })
await p.waitForTimeout(2500)
console.log('быстрые действия:', await p.getByTestId('room-quick-actions').count())
const q = p.locator('[data-testid^="room-quick-"]')
console.log('кнопок:', await q.count(), await q.allInnerTexts())
console.log('статусы заявок:', await p.getByTestId('room-request-statuses').count())
await b.close()
