import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ locale: 'ru-RU' })
p.on('pageerror', e => console.log('PAGEERROR', String(e).slice(0,200)))
await p.goto('http://localhost:5183/login')
await p.getByTestId('login-email').fill('owner@crystal.local')
await p.getByTestId('login-password').fill('chef12345')
await p.getByTestId('login-submit').click()
await p.waitForURL(/\/cms\//)
await p.goto('http://localhost:5183/cms/room-control')
await p.getByTestId('grms-type-select').locator('[role="combobox"]').click()
await p.locator('li[data-value="tip3"]').click()
await p.getByTestId('grms-tab-plan').click()
await p.waitForTimeout(2500)
console.log('сцена есть:', await p.getByTestId('grms-plan-stage').count(), '| нет кадра:', await p.getByTestId('grms-plan-no-frame').count())
console.log('ночной:', await p.getByTestId('grms-plan-night-state').innerText().catch(()=>'-'))
if (await p.getByTestId('grms-plan-stage').count()) {
  await p.getByTestId('grms-plan-tool-zone').click()
  const box = await p.getByTestId('grms-plan-stage').boundingBox()
  console.log('box', box)
  await p.mouse.move(box.x + box.width*0.55, box.y + box.height*0.55)
  await p.mouse.down()
  await p.mouse.move(box.x + box.width*0.8, box.y + box.height*0.85, {steps: 8})
  await p.mouse.up()
  await p.waitForTimeout(600)
  console.log('зон после:', await p.locator('[data-testid^="grms-plan-zone-"]').count())
}
await b.close()
