import { chromium } from '@playwright/test'
import { STORAGE_KEYS } from './fixtures/appState.mjs'
const b = await chromium.launch()
const p = await b.newPage({ viewport: {width: 390, height: 844}, locale: 'ru-RU', deviceScaleFactor: 2 })
await p.goto('http://localhost:5183')
await p.evaluate(() => { localStorage.clear(); sessionStorage.clear(); localStorage.setItem(STORAGE_KEYS.theme,'dark') })
await p.goto('http://localhost:5183')
await p.getByTestId('guest-room-input').fill('305')
await p.getByTestId('guest-room-submit').click()
await p.getByTestId('guest-nav-room').click()
await p.getByTestId('room-page').waitFor({ timeout: 20000 })
await p.waitForTimeout(2500)
await p.evaluate(() => window.scrollTo(0, 240))
await p.waitForTimeout(600)
await p.screenshot({ path: '../docs/design/g10-shots/room-phone-dark-scroll240.png' })
await b.close()
