# Generated by Django 5.2.16 on 2026-07-21 14:44

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('hotels', '0002_executionpoint_sla_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_mode',
            field=models.CharField(choices=[('delivery', 'Спросить локацию'), ('room', 'Номер гостя'), ('none', 'Локация не нужна')], default='delivery', help_text='Спрашивать ли у гостя локацию доставки', max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('product', 'Товар/блюдо'), ('service_request', 'Заявка-услуга')], default='product', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='В минимальных единицах (копейках)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('product', 'Товар/блюдо'), ('service_request', 'Заявка-услуга')], default='product', max_length=32),
        ),
        migrations.CreateModel(
            name='RequestField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('label', apps.core.fields.TranslatableField()),
                ('help_text', apps.core.fields.TranslatableField()),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('count', 'Количество'), ('date', 'Дата'), ('time', 'Время'), ('select', 'Выбор из списка')], default='text', max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_fields', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_request_field',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('item', 'code'), name='uniq_request_field_per_item')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
