# Generated by Django 5.2.16 on 2026-07-22 00:10

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_location_mode_alter_category_type_and_more'),
        ('hotels', '0003_executionpoint_schedule_location_schedule_room_zone'),
        ('orders', '0004_order_field_values_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=apps.core.fields.TranslatableField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('product', 'Товар/блюдо'), ('service_request', 'Заявка-услуга'), ('info', 'Инфо-страница'), ('slot', 'Бронь слота')], default='product', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('product', 'Товар/блюдо'), ('service_request', 'Заявка-услуга'), ('info', 'Инфо-страница'), ('slot', 'Бронь слота')], default='product', max_length=32),
        ),
        migrations.CreateModel(
            name='SlotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('lead_minutes', models.PositiveSmallIntegerField(default=0)),
                ('horizon_days', models.PositiveSmallIntegerField(default=14)),
                ('execution_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_configs', to='hotels.executionpoint')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_config', to='catalog.item')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hotels.schedule')),
            ],
            options={
                'db_table': 'catalog_slot_config',
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='orders.order')),
            ],
            options={
                'db_table': 'catalog_slot_booking',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['hotel', 'item', 'starts_at', 'is_active'], name='catalog_slo_hotel_i_7d2614_idx')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
