# Generated by Django 5.2.16 on 2026-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_content_alter_category_type_alter_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_order_minor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='service_fee_applies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='prep_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
