# Generated by Django 5.2.16 on 2026-07-22 23:34

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_min_order_minor_and_more'),
        ('hotels', '0005_executionpoint_min_order_minor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', apps.core.fields.TranslatableField()),
                ('color_role', models.CharField(choices=[('accent', 'Акцент'), ('gold', 'Золото'), ('success', 'Успех'), ('info', 'Инфо')], default='accent', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('preset', models.SlugField(blank=True, max_length=64)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'catalog_badge',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_badges', to='catalog.badge')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_badges', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_item_badge',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'item', 'badge'), name='uniq_item_badge')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
