# Generated by Django 5.2.16 on 2026-07-24 10:00

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_badge_itembadge'),
        ('hotels', '0009_executionpoint_guest_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'catalog_allergen',
                'ordering': ['sort_order', 'code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DietaryMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'catalog_dietary_marker',
                'ordering': ['sort_order', 'code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allergens', to='catalog.allergen')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allergens', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_item_allergen',
                'ordering': ['allergen__sort_order'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', apps.core.fields.TranslatableField()),
                ('value', apps.core.fields.TranslatableField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_item_characteristic',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemDietaryMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_markers', to='catalog.item')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_markers', to='catalog.dietarymarker')),
            ],
            options={
                'db_table': 'catalog_item_dietary_marker',
                'ordering': ['marker__sort_order'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_allergen_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='dietarymarker',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_dietary_marker_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='itemallergen',
            constraint=models.UniqueConstraint(fields=('hotel', 'item', 'allergen'), name='uniq_item_allergen'),
        ),
        migrations.AddConstraint(
            model_name='itemdietarymarker',
            constraint=models.UniqueConstraint(fields=('hotel', 'item', 'marker'), name='uniq_item_marker'),
        ),
    ]
