# Generated by Django 5.2.16 on 2026-07-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_backfill_item_facets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='item',
            name='flags',
        ),
    ]
