# Generated by Django 5.2.16 on 2026-07-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_item_allergens_remove_item_flags'),
        ('hotels', '0010_service_hotelmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='hotels.service'),
        ),
    ]
