# Generated by Django 5.2.16 on 2026-07-30 14:27

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_service'),
        ('hotels', '0012_drop_executionpoint_guest_commerce'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(choices=[('all', 'Весь источник'), ('categories', 'Выбранные категории')], default='all', max_length=16)),
                ('markup_kind', models.CharField(choices=[('none', 'Без наценки'), ('percent', 'Процент'), ('amount', 'Сумма')], default='none', max_length=16)),
                ('markup_value', models.IntegerField(default=0)),
                ('executor', models.CharField(choices=[('source', 'Точка источника'), ('own', 'Своя точка')], default='source', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('including_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='hotels.service')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.schedule')),
                ('source_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_uses', to='hotels.service')),
            ],
            options={
                'db_table': 'catalog_service_inclusion',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceInclusionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_selections', to='catalog.category')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_categories', to='catalog.serviceinclusion')),
            ],
            options={
                'db_table': 'catalog_service_inclusion_category',
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceInclusionHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_items', to='catalog.serviceinclusion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_hidden_in', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_service_inclusion_hidden',
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='serviceinclusion',
            constraint=models.UniqueConstraint(fields=('hotel', 'including_service', 'source_service'), name='uniq_inclusion_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='serviceinclusion',
            constraint=models.CheckConstraint(condition=models.Q(('including_service', models.F('source_service')), _negated=True), name='inclusion_no_self'),
        ),
        migrations.AddConstraint(
            model_name='serviceinclusioncategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'inclusion', 'category'), name='uniq_inclusion_category'),
        ),
        migrations.AddConstraint(
            model_name='serviceinclusionhidden',
            constraint=models.UniqueConstraint(fields=('hotel', 'inclusion', 'item'), name='uniq_inclusion_hidden'),
        ),
    ]
