# Generated by Django 5.2.17 on 2026-09-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_drop_dead_matrix_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
