# Generated by Django 5.2.17 on 2026-09-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_internal_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfield',
            name='sets_requested_time',
            field=models.BooleanField(default=False),
        ),
    ]
