# Generated by Django 5.2.17 on 2026-10-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_request_field_sets_requested_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelocation',
            name='delivery_modes',
        ),
    ]
