# Generated by Django 5.2.17 on 2026-10-08 00:09

from django.db import migrations, models

from apps.core.migration_guards import assert_no_live_duplicates


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_drop_service_location_delivery_modes'),
        ('hotels', '0042_telegram_bot'),
        ('media', '0006_alter_mediaasset_kind'),
    ]

    operations = [
        # Сначала — живых дублей нет (п.76): иначе условный индекс упадёт посреди
        # миграции невнятной ошибкой Postgres. Обратного хода сторожу не нужно.
        migrations.RunPython(
            assert_no_live_duplicates([
                ("catalog", "Allergen", ("code",)),
                ("catalog", "Category", ("code",)),
                ("catalog", "DietaryMarker", ("code",)),
                ("catalog", "Item", ("code",)),
                ("catalog", "ModifierGroup", ("item_id", "code")),
                ("catalog", "ModifierOption", ("group_id", "code")),
                ("catalog", "RequestField", ("item_id", "code")),
            ]),
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='allergen',
            name='uniq_allergen_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_code_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='dietarymarker',
            name='uniq_dietary_marker_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_code_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='modifiergroup',
            name='uniq_modifier_group_per_item',
        ),
        migrations.RemoveConstraint(
            model_name='modifieroption',
            name='uniq_modifier_option_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='requestfield',
            name='uniq_request_field_per_item',
        ),
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_allergen_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_category_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='dietarymarker',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_dietary_marker_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_item_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('item', 'code'), name='uniq_modifier_group_per_item'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'code'), name='uniq_modifier_option_per_group'),
        ),
        migrations.AddConstraint(
            model_name='requestfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('item', 'code'), name='uniq_request_field_per_item'),
        ),
    ]
