# Generated by Django 5.2.16 on 2026-08-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_platform_role_user_totp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='room_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
