# Generated by Django 5.2.17 on 2026-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_impersonation_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonationgrant',
            name='actor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
