# Generated by Django 5.2.17 on 2026-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsession',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='refresh_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
