# Generated by Django 5.2.16 on 2026-08-02 16:51

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0015_onboardingtemplate_systemdictionaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('device_name_template', models.CharField(blank=True, max_length=255)),
                ('subdevice', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'grms_room_type',
                'ordering': ['code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublishedConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.UUIDField(blank=True, null=True)),
                ('rolled_back_from', models.PositiveIntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_configs', to='grms.roomtype')),
            ],
            options={
                'db_table': 'grms_published_config',
                'ordering': ['-version'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ControlElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=64)),
                ('kind', models.CharField(choices=[('dnd', 'Не беспокоить'), ('mur', 'Убрать номер'), ('master_switch', 'Мастер-выключатель'), ('light_group', 'Группа света'), ('curtain', 'Шторы'), ('curtain_blackout', 'Блэкаут-шторы'), ('air_conditioner', 'Кондиционер'), ('heating', 'Отопление'), ('scene', 'Сцена')], max_length=32)),
                ('title', apps.core.fields.TranslatableField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='grms.roomtype')),
            ],
            options={
                'db_table': 'grms_control_element',
                'ordering': ['sort_order', 'slug'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoomTypeRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_reference', models.BooleanField(default=False)),
                ('device_name_override', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grms_type_link', to='hotels.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='grms.roomtype')),
            ],
            options={
                'db_table': 'grms_room_type_room',
                'ordering': ['room_id'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.SlugField(max_length=64)),
                ('command', models.CharField(blank=True, max_length=128)),
                ('feedback', models.CharField(blank=True, max_length=128)),
                ('value_kind', models.CharField(choices=[('binary', '0/1'), ('enum', 'Дискретный набор'), ('range', 'Диапазон')], default='binary', max_length=16)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=1)),
                ('raw_range', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='grms.roomtype')),
            ],
            options={
                'db_table': 'grms_variable',
                'ordering': ['key'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('capability', models.CharField(choices=[('toggle', 'toggle'), ('trigger', 'trigger'), ('fan_speed', 'fan_speed'), ('setpoint', 'setpoint'), ('current_temp', 'current_temp'), ('position', 'position'), ('level', 'level')], max_length=32)),
                ('trigger_value', models.IntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='grms.controlelement')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='grms.variable')),
            ],
            options={
                'db_table': 'grms_binding',
                'ordering': ['capability'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='grms.roomtype')),
            ],
            options={
                'db_table': 'grms_zone',
                'ordering': ['sort_order', 'code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='controlelement',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='grms.zone'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_grms_room_type_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='publishedconfig',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_type', 'version'), name='uniq_grms_config_version'),
        ),
        migrations.AddConstraint(
            model_name='publishedconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('hotel', 'room_type'), name='uniq_grms_current_config_per_type'),
        ),
        migrations.AddConstraint(
            model_name='roomtyperoom',
            constraint=models.UniqueConstraint(fields=('hotel', 'room'), name='uniq_grms_room_link_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_type', 'key'), name='uniq_grms_variable_per_type'),
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(fields=('hotel', 'element', 'capability'), name='uniq_grms_binding_per_element'),
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(fields=('hotel', 'variable'), name='uniq_grms_variable_used_once'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_type', 'code'), name='uniq_grms_zone_per_type'),
        ),
        migrations.AddConstraint(
            model_name='controlelement',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_type', 'slug'), name='uniq_grms_element_per_type'),
        ),
    ]
