# Generated by Django 5.2.16 on 2026-08-03 17:47

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0001_initial'),
        ('hotels', '0015_onboardingtemplate_systemdictionaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pin_hash', models.CharField(max_length=256)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grms_pin', to='hotels.room')),
            ],
            options={
                'db_table': 'grms_room_pin',
                'ordering': ['room_id'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'room'), name='uniq_grms_pin_per_room')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
