# Generated by Django 5.2.16 on 2026-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0003_roomtype_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelement',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='zone',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
