# Generated by Django 5.2.16 on 2026-08-06 00:30

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0004_controlelement_icon_zone_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelement',
            name='hint',
            field=apps.core.fields.TranslatableField(),
        ),
    ]
