# Generated by Django 5.2.17 on 2026-10-08 00:09

from django.db import migrations, models

from apps.core.migration_guards import assert_no_live_duplicates


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0006_roomtype_plan_level'),
        ('hotels', '0043_codes_unique_among_live'),
    ]

    operations = [
        # Сначала — живых дублей нет (п.76): иначе условный индекс упадёт посреди
        # миграции невнятной ошибкой Postgres. Обратного хода сторожу не нужно.
        migrations.RunPython(
            assert_no_live_duplicates([
                ("grms", "Binding", ("element_id", "capability")),
                ("grms", "Binding", ("variable_id",)),
            ]),
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='binding',
            name='uniq_grms_binding_per_element',
        ),
        migrations.RemoveConstraint(
            model_name='binding',
            name='uniq_grms_variable_used_once',
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'element', 'capability'), name='uniq_grms_binding_per_element'),
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'variable'), name='uniq_grms_variable_used_once'),
        ),
    ]
