# Generated by Django 5.2.16 on 2026-07-21 11:33

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPlaceholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('image_url', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'media_category_placeholder',
                'ordering': ['code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('item', 'Позиция каталога'), ('category', 'Категория'), ('brand', 'Брендинг'), ('other', 'Прочее')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('object_key', models.CharField(help_text='Ключ оригинала в бакете', max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('alt', apps.core.fields.TranslatableField()),
                ('error', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'media_asset',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
