# Generated by Django 5.2.16 on 2026-08-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediaasset_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='luminance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
