# Generated by Django 5.2.17 on 2026-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediaasset_luminance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='crop',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='crop_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
