# Generated by Django 5.2.17 on 2026-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_mediaasset_crop_mediaasset_crop_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('item', 'Позиция каталога'), ('category', 'Категория'), ('brand', 'Брендинг'), ('room_plan', 'План номера'), ('font', 'Шрифт'), ('other', 'Прочее')], default='other', max_length=32),
        ),
    ]
