# Generated by Django 5.2.17 on 2026-09-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_font_asset_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('item', 'Позиция каталога'), ('category', 'Категория'), ('brand', 'Брендинг'), ('room_plan', 'План номера'), ('font', 'Шрифт'), ('banner', 'Рекламный баннер'), ('other', 'Прочее')], default='other', max_length=32),
        ),
    ]
