# Generated by Django 5.2.16 on 2026-07-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionpoint',
            name='sla_minutes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
