# Generated by Django 5.2.16 on 2026-07-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_executionpoint_sla_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionpoint',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.schedule'),
        ),
        migrations.AddField(
            model_name='location',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.schedule'),
        ),
        migrations.AddField(
            model_name='room',
            name='zone',
            field=models.CharField(blank=True, help_text='Корпус, крыло, зона', max_length=64),
        ),
    ]
