# Generated by Django 5.2.16 on 2026-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_executionpoint_schedule_location_schedule_room_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='review_low_threshold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
