# Generated by Django 5.2.16 on 2026-07-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_review_enabled_hotel_review_low_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionpoint',
            name='min_order_minor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='free_delivery_threshold_minor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_round_to_minor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_fee_bp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tax_bp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tax_inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tip_presets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='location',
            name='delivery_fee_minor',
            field=models.IntegerField(default=0),
        ),
    ]
