# Generated by Django 5.2.16 on 2026-07-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_executionpoint_min_order_minor_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionpoint',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset'),
        ),
    ]
