# Generated by Django 5.2.16 on 2026-07-23 23:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_executionpoint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='showcase_group_threshold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='ShowcaseTile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.SlugField(max_length=80)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L')], default='m', max_length=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotels_showcase_tile',
                'ordering': ['sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'key'), name='uniq_showcase_tile_per_hotel')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
