# Generated by Django 5.2.16 on 2026-07-24 07:50

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_showcase_group_threshold_showcasetile'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionpoint',
            name='is_guest_facing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='executionpoint',
            name='public_name',
            field=apps.core.fields.TranslatableField(),
        ),
        migrations.AddField(
            model_name='executionpoint',
            name='tagline',
            field=apps.core.fields.TranslatableField(),
        ),
    ]
