# Generated by Django 5.2.16 on 2026-07-30 08:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_executionpoint_guest_backfill'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tariff',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='HotelModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('tariff', 'По тарифу'), ('override', 'Переопределение (вне тарифа)')], default='tariff', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotels_hotel_module',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_module_per_hotel')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('type', models.CharField(choices=[('restaurant', 'Ресторан'), ('bar', 'Бар'), ('room_service', 'Рум-сервис'), ('spa', 'SPA'), ('pool', 'Бассейн'), ('transfer', 'Трансфер/такси'), ('concierge', 'Консьерж'), ('excursions', 'Экскурсии'), ('housekeeping', 'Хозслужба'), ('minibar', 'Мини-бар/магазин'), ('info', 'Инфо-раздел'), ('custom', 'Свой')], default='custom', max_length=32)),
                ('public_name', apps.core.fields.TranslatableField()),
                ('tagline', apps.core.fields.TranslatableField()),
                ('is_guest_facing', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('service_fee_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('tip_presets', models.JSONField(blank=True, null=True)),
                ('min_order_minor', models.IntegerField(blank=True, null=True)),
                ('free_delivery_threshold_minor', models.IntegerField(blank=True, null=True)),
                ('price_round_to_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='hotels.executionpoint')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.schedule')),
            ],
            options={
                'db_table': 'hotels_service',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_service_per_hotel'), models.UniqueConstraint(fields=('hotel', 'execution_point'), name='uniq_service_per_execution_point')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
