# Generated by Django 5.2.16 on 2026-07-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_backfill_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionpoint',
            name='image',
        ),
        migrations.RemoveField(
            model_name='executionpoint',
            name='is_guest_facing',
        ),
        migrations.RemoveField(
            model_name='executionpoint',
            name='min_order_minor',
        ),
        migrations.RemoveField(
            model_name='executionpoint',
            name='public_name',
        ),
        migrations.RemoveField(
            model_name='executionpoint',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='executionpoint',
            name='tagline',
        ),
    ]
