# Generated by Django 5.2.16 on 2026-07-31 20:26

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_drop_executionpoint_guest_commerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tariff_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OnPremNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('grms', 'Управление номером'), ('pms', 'PMS'), ('both', 'GRMS + PMS')], default='grms', max_length=16)),
                ('key_hash', models.CharField(blank=True, max_length=64)),
                ('key_issued_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotels_onprem_node',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_node_per_hotel')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
