# Generated by Django 5.2.16 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotel_tariff_started_on_hotel_trial_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='origin',
            field=models.CharField(choices=[('live', 'Боевой'), ('demo', 'Демонстрационный'), ('test', 'Создан автотестом')], db_index=True, default='live', max_length=8),
        ),
    ]
