# Generated by Django 5.2.16 on 2026-07-31 21:01

import apps.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', apps.core.fields.TranslatableField()),
                ('description', apps.core.fields.TranslatableField()),
                ('tariff', models.CharField(blank=True, max_length=64)),
                ('services', models.JSONField(blank=True, default=list)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('preset', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hotels_onboarding_template',
                'ordering': ['sort_order', 'code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemDictionaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('allergen', 'Аллерген'), ('marker', 'Диетический маркер')], max_length=16)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hotels_system_dictionary',
                'ordering': ['kind', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'code'), name='uniq_system_dict_entry')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
