# Generated by Django 5.2.16 on 2026-08-08 01:35

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=apps.core.fields.TranslatableField(),
        ),
    ]
