# Generated by Django 5.2.17 on 2026-08-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_hotel_name_translatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='former_subdomain',
            field=models.SlugField(blank=True, max_length=63),
        ),
    ]
