# Generated by Django 5.2.17 on 2026-08-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_hotel_former_subdomain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('custom_domain', ''), _negated=True)), fields=('custom_domain',), name='uniq_custom_domain_alive'),
        ),
    ]
