# Generated by Django 5.2.17 on 2026-08-26 00:28

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_execution_point_sla_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('network', 'Сеть'), ('brand', 'Бренд'), ('city', 'Город'), ('test', 'Тестовые'), ('campaign', 'Кампания'), ('custom', 'Своя')], default='custom', max_length=16)),
                ('mode', models.CharField(choices=[('list', 'Список'), ('rule', 'Правило')], default='list', max_length=8)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hotels_group',
                'ordering': ['kind', 'title'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HotelGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('added_by', models.UUIDField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hotels.hotelgroup')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotels_group_member',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'hotel'), name='uniq_group_hotel')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
