# Generated by Django 5.2.17 on 2026-08-26 09:33

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_hotel_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.SlugField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scope', models.CharField(choices=[('hotels', 'Выбранные отели'), ('group', 'Группа'), ('all', 'Все отели')], default='hotels', max_length=16)),
                ('hotel_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Идёт'), ('done', 'Завершена'), ('failed', 'Не выполнена')], default='pending', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('planned', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hotels.hotelgroup')),
            ],
            options={
                'db_table': 'hotels_publication_job',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outcome', models.CharField(choices=[('applied', 'Применено'), ('skipped', 'Пропущено'), ('refused', 'Отказано'), ('failed', 'Ошибка')], max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hotels.hotel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hotels.publicationjob')),
            ],
            options={
                'db_table': 'hotels_publication_result',
                'ordering': ['hotel_id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'hotel'), name='uniq_publication_result')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
