# Generated by Django 5.2.17 on 2026-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationresult',
            name='reason',
            field=models.SlugField(blank=True, max_length=32),
        ),
    ]
