# Generated by Django 5.2.17 on 2026-08-26 15:43

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_publication_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformScopeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_users', to='hotels.hotelgroup')),
            ],
            options={
                'db_table': 'hotels_platform_scope_group',
                'ordering': ['user_id'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'group'), name='uniq_platform_scope')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
