# Generated by Django 5.2.17 on 2026-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_platform_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtheme',
            name='source_preset',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
    ]
