# Generated by Django 5.2.17 on 2026-09-14 17:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_backfill_theme_source_preset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('author_name', models.CharField(blank=True, default='', max_length=180)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_versions', to=settings.AUTH_USER_MODEL)),
                ('base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts_from', to='hotels.brandversion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='hotels.brandversion')),
            ],
            options={
                'db_table': 'hotels_brand_version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'kind', '-created_at'], name='hotels_bran_hotel_i_254438_idx')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
