"""
Поля номерного фонда: категория, уборка, «вне продажи», порядок этажей.

ЧЕГО ЗДЕСЬ НЕТ — ЗАНЯТОСТИ. Её неоткуда взять: PMS не получен, а ручной
статус, который никто не обновляет, — это экран, который врёт. Уборка и
«вне продажи» заводятся, потому что их ставит персонал по-настоящему.

«ВНЕ ПРОДАЖИ» — отдельный флаг, а не `is_active`: последний закрывает ВХОД
гостя и убирает номер из печатного листа QR (см. комментарий в модели).

КАТЕГОРИЯ — своя таблица на стороне hotels, а не `grms.RoomType`: тот про
оборудование, включается тарифом и связан с комнатой OneToOne.

Бэкфилл — ключ этажа у существующих номеров, по отелям с `tenant_context`:
`Room` тенантная, и под обычной ролью без тенанта запрос вернёт ноль строк, а
не ошибку.
"""

# Generated by Django 5.2.17 on 2026-09-16 06:32

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.context import tenant_context
from apps.hotels.models.room import natural_number_key


def backfill_floor_key(apps, schema_editor):
    db = schema_editor.connection.alias
    Hotel = apps.get_model("hotels", "Hotel")
    Room = apps.get_model("hotels", "Room")

    touched = 0
    for hotel in Hotel.objects.using(db).all():
        with tenant_context(hotel.pk):
            for room in Room.objects.using(db).filter(hotel_id=hotel.pk):
                room.floor_key = natural_number_key(room.floor)
                room.save(update_fields=["floor_key"])
                touched += 1

    for hotel in Hotel.objects.using(db).all():
        with tenant_context(hotel.pk):
            for room in Room.objects.using(db).filter(hotel_id=hotel.pk):
                expected = natural_number_key(room.floor)
                if room.floor_key != expected:
                    raise RuntimeError(
                        f"номер {room.number}: ключ этажа «{room.floor_key}» вместо "
                        f"«{expected}» — бэкфилл не доехал"
                    )
    print(f"  ключ этажа проставлен: {touched} номеров")


def noop(apps, schema_editor):
    """Обратный ход: колонка уносится целиком, восстанавливать нечего."""


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0032_room_number_free_after_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping',
            field=models.CharField(choices=[('unknown', 'Неизвестно'), ('clean', 'Чисто'), ('dirty', 'Грязно'), ('in_progress', 'Убирается')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='out_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('title', apps.core.fields.TranslatableField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'hotels_room_category',
                'ordering': ['sort_order', 'code'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotels.roomcategory'),
        ),
        migrations.AddConstraint(
            model_name='roomcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_room_category_per_hotel'),
        ),
        migrations.RunPython(backfill_floor_key, noop),
    ]
