"""
Признак «есть каталог» у заведения (пункт 10 заказчика).

Ресепшен (точка `reception`) — отдел без меню: признак снят у каждого
ресепшена, у которого нет ни одного раздела. Ресепшен, где отель всё же
завёл разделы, не трогаем — меню не прячем молча.
"""
# Generated by Django 5.2.17 on 2026-09-17 14:33

from django.db import migrations, models


def reception_without_menu(apps_registry, schema_editor):
    Service = apps_registry.get_model("hotels", "Service")
    Category = apps_registry.get_model("catalog", "Category")
    db = schema_editor.connection.alias
    with_categories = Category._base_manager.using(db).filter(
        deleted_at__isnull=True, service_id__isnull=False
    ).values("service_id")
    changed = (
        Service._base_manager.using(db)
        .filter(execution_point__code="reception")
        .exclude(pk__in=with_categories)
        .update(has_catalog=False)
    )
    print(f"\n    ресепшенов без каталога: {changed}")


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_review_low_threshold_two'),
        ('catalog', '0013_drop_dead_matrix_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_catalog',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(reception_without_menu, migrations.RunPython.noop),
    ]
