# Generated by Django 5.2.17 on 2026-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_service_has_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='chat_reply_minutes',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
