# Generated by Django 5.2.17 on 2026-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_chat_reply_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='temperature_units',
            field=models.CharField(choices=[('c', 'Цельсий'), ('f', 'Фаренгейт')], default='c', max_length=1),
        ),
    ]
