# Generated by Django 5.2.17 on 2026-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_zones_to_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='telegram_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
