# Generated by Django 5.2.17 on 2026-10-08 00:09

from django.db import migrations, models

from apps.core.migration_guards import assert_no_live_duplicates


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0042_telegram_bot'),
        ('media', '0006_alter_mediaasset_kind'),
    ]

    operations = [
        # Сначала — живых дублей нет (п.76): иначе условный индекс упадёт посреди
        # миграции невнятной ошибкой Postgres. Обратного хода сторожу не нужно.
        migrations.RunPython(
            assert_no_live_duplicates([
                ("hotels", "ExecutionPoint", ("code",)),
                ("hotels", "Location", ("code",)),
                ("hotels", "Service", ("code",)),
            ]),
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='executionpoint',
            name='uniq_execution_point_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='uniq_location_per_hotel',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='uniq_service_per_hotel',
        ),
        migrations.AddConstraint(
            model_name='executionpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_execution_point_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_location_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('hotel', 'code'), name='uniq_service_per_hotel'),
        ),
    ]
