"""
Статус разбора отзыва и журнал шагов разбора.

Старые отзывы (до волны 8): низкие — «новый», их есть смысл разобрать;
остальные — «закрыт», чтобы список «ждут разбора» не начинался с сотни
пятёрок, которым никто и не собирался отвечать. Шагов разбора им не
придумываем: журнала тогда не было.
"""
# Generated by Django 5.2.17 on 2026-09-17 10:32

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def close_old_high(apps_registry, schema_editor):
    Review = apps_registry.get_model("reviews", "Review")
    db = schema_editor.connection.alias
    closed = (
        Review.objects.using(db)
        .filter(rating__gt=models.F("low_threshold"))
        .update(triage_status="closed")
    )
    print(f"\n    старых отзывов не ниже порога закрыто без разбора: {closed}")


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_review_low_threshold_two'),
        ('reviews', '0004_review_low_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='triage_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'Разбирается'), ('closed', 'Закрыт')], db_index=True, default='new', max_length=16),
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'Новый'), ('in_progress', 'Разбирается'), ('closed', 'Закрыт')], max_length=16)),
                ('to_status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'Разбирается'), ('closed', 'Закрыт')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reviews.review')),
            ],
            options={
                'db_table': 'reviews_action',
                'ordering': ['created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.RunPython(close_old_high, migrations.RunPython.noop),
    ]
