"""Отметки последнего сообщения гостя и персонала; старые треды — по сообщениям."""
# Generated by Django 5.2.17 on 2026-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_threads_to_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='last_guest_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='last_staff_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        ]
