# Generated by Django 5.2.17 on 2026-09-17 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_contacts'),
        ('chat', '0008_merge_duplicate_session_threads'),
        ('hotels', '0036_service_has_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_session__isnull', False)), fields=('guest_session',), name='uniq_chat_thread_per_guest_session'),
        ),
    ]
