# Generated by Django 5.2.17 on 2026-09-18 08:47

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0039_translatable_strings_to_maps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('languages', models.JSONField(default=list)),
                ('groups', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Идёт'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('translated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('characters', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translate_run',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TranslationMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('app_label', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('object_id', models.UUIDField()),
                ('field', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=8)),
                ('value_hash', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('characters', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'translate_mark',
                'indexes': [models.Index(fields=['hotel', 'language'], name='translate_m_hotel_i_822787_idx')],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'app_label', 'model', 'object_id', 'field', 'language'), name='uniq_translation_mark')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TranslationUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(max_length=7)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('characters', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='hotels.hotel')),
            ],
            options={
                'db_table': 'translate_usage',
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('hotel', 'period'), name='uniq_translation_usage')],
            },
            bases=(apps.core.fields.TranslatableMixin, models.Model),
        ),
    ]
